name: 'fabric1project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  fabric1project:
    staging:
      +materialized: table
      #schema: analytics
      database: dwh
    intermediate-silver:
      +materialized: table
      #schema: analytics
      database: dwh_silver
    marts-gold:
      +materialized: table
      #schema: analytics
      database: dwh_gold

