{{ config( materialized='view' ) }}

with 

source as (

    select * from {{ source('source_tables', 'source1') }}

),

renamed as (

    select
        CAST(PK as INTEGER) as pk,
        Column_1,
        Column_2,
        Column_3,
        Column_4,
        Column_5,
        Column_6,
        Column_7,
        Column_8,
        Column_9,
        Column_10,
        Column_11,
        Column_12,
        Column_13,
        Column_14,
        Column_15,
        Column_16,
        Column_17,
        Column_18,
        Column_19,
        Column_20,
        Column_21,
        Column_22,
        Column_23,
        Column_24,
        Column_25,
        Column_26,
        Column_27,
        Column_28,
        Column_29,
        Column_30,
        Column_31,
        Column_32,
        Column_33,
        Column_34,
        Column_35,
        Column_36,
        Column_37,
        Column_38,
        Column_39,
        Column_40,
        Column_41,
        Column_42,
        Column_43,
        Column_44,
        Column_45,
        Column_46,
        Column_47,
        Column_48,
        Column_49,
        Column_50,
        Column_51,
        Column_52,
        Column_53,
        Column_54,
        Column_55,
        Column_56,
        Column_57,
        Column_58,
        Column_59,
        Column_60,
        Column_61,
        Column_62,
        Column_63,
        Column_64,
        Column_65,
        Column_66,
        Column_67,
        Column_68,
        Column_69,
        Column_70,
        Column_71,
        Column_72,
        Column_73,
        Column_74,
        Column_75,
        Column_76,
        Column_77,
        Column_78,
        Column_79,
        Column_80,
        Column_81,
        Column_82,
        Column_83,
        Column_84,
        Column_85,
        Column_86,
        Column_87,
        Column_88,
        Column_89,
        Column_90,
        Column_91,
        Column_92,
        Column_93,
        Column_94,
        Column_95,
        Column_96,
        Column_97,
        Column_98,
        Column_99,
        Column_100,
        Column_101,
        Column_102,
        Column_103,
        Column_104,
        Column_105,
        Column_106,
        Column_107,
        Column_108,
        Column_109,
        Column_110,
        Column_111,
        Column_112,
        Column_113,
        Column_114,
        Column_115,
        Column_116,
        Column_117,
        Column_118,
        Column_119,
        Column_120,
        Column_121,
        Column_122,
        Column_123,
        Column_124,
        Column_125,
        Column_126,
        Column_127,
        Column_128,
        Column_129,
        Column_130,
        Column_131,
        Column_132,
        Column_133,
        Column_134,
        Column_135,
        Column_136,
        Column_137,
        Column_138,
        Column_139,
        Column_140,
        Column_141,
        Column_142,
        Column_143,
        Column_144,
        Column_145,
        Column_146,
        Column_147,
        Column_148,
        Column_149,
        Column_150,
        Column_151,
        Column_152,
        Column_153,
        Column_154,
        Column_155,
        Column_156,
        Column_157,
        Column_158,
        Column_159,
        Column_160,
        Column_161,
        Column_162,
        Column_163,
        Column_164,
        Column_165,
        Column_166,
        Column_167,
        Column_168,
        Column_169,
        Column_170,
        Column_171,
        Column_172,
        Column_173,
        Column_174,
        Column_175,
        Column_176,
        Column_177,
        Column_178,
        Column_179,
        Column_180,
        Column_181,
        Column_182,
        Column_183,
        Column_184,
        Column_185,
        Column_186,
        Column_187,
        Column_188,
        Column_189,
        Column_190,
        Column_191,
        Column_192,
        Column_193,
        Column_194,
        Column_195,
        Column_196,
        Column_197,
        Column_198,
        Column_199,
        Column_200,
        updated_at,
        CONVERT(varchar(32), HASHBYTES('MD5', 
            CONCAT_WS('|', 
                CAST(PK AS VARCHAR(MAX)),
                CAST(Column_1 AS VARCHAR(MAX)),
                CAST(Column_2 AS VARCHAR(MAX)),
                CAST(Column_3 AS VARCHAR(MAX)),
                CAST(Column_4 AS VARCHAR(MAX)),
                CAST(Column_5 AS VARCHAR(MAX)),
                CAST(Column_6 AS VARCHAR(MAX)),
                CAST(Column_7 AS VARCHAR(MAX)),
                CAST(Column_8 AS VARCHAR(MAX)),
                CAST(Column_9 AS VARCHAR(MAX)),
                CAST(Column_10 AS VARCHAR(MAX)),
                CAST(Column_11 AS VARCHAR(MAX)),
                CAST(Column_12 AS VARCHAR(MAX)),
                CAST(Column_13 AS VARCHAR(MAX)),
                CAST(Column_14 AS VARCHAR(MAX)),
                CAST(Column_15 AS VARCHAR(MAX)),
                CAST(Column_16 AS VARCHAR(MAX)),
                CAST(Column_17 AS VARCHAR(MAX)),
                CAST(Column_18 AS VARCHAR(MAX)),
                CAST(Column_19 AS VARCHAR(MAX)),
                CAST(Column_20 AS VARCHAR(MAX)),
                CAST(Column_21 AS VARCHAR(MAX)),
                CAST(Column_22 AS VARCHAR(MAX)),
                CAST(Column_23 AS VARCHAR(MAX)),
                CAST(Column_24 AS VARCHAR(MAX)),
                CAST(Column_25 AS VARCHAR(MAX)),
                CAST(Column_26 AS VARCHAR(MAX)),
                CAST(Column_27 AS VARCHAR(MAX)),
                CAST(Column_28 AS VARCHAR(MAX)),
                CAST(Column_29 AS VARCHAR(MAX)),
                CAST(Column_30 AS VARCHAR(MAX)),
                CAST(Column_31 AS VARCHAR(MAX)),
                CAST(Column_32 AS VARCHAR(MAX)),
                CAST(Column_33 AS VARCHAR(MAX)),
                CAST(Column_34 AS VARCHAR(MAX)),
                CAST(Column_35 AS VARCHAR(MAX)),
                CAST(Column_36 AS VARCHAR(MAX)),
                CAST(Column_37 AS VARCHAR(MAX)),
                CAST(Column_38 AS VARCHAR(MAX)),
                CAST(Column_39 AS VARCHAR(MAX)),
                CAST(Column_40 AS VARCHAR(MAX)),
                CAST(Column_41 AS VARCHAR(MAX)),
                CAST(Column_42 AS VARCHAR(MAX)),
                CAST(Column_43 AS VARCHAR(MAX)),
                CAST(Column_44 AS VARCHAR(MAX)),
                CAST(Column_45 AS VARCHAR(MAX)),
                CAST(Column_46 AS VARCHAR(MAX)),
                CAST(Column_47 AS VARCHAR(MAX)),
                CAST(Column_48 AS VARCHAR(MAX)),
                CAST(Column_49 AS VARCHAR(MAX)),
                CAST(Column_50 AS VARCHAR(MAX)),
                CAST(Column_51 AS VARCHAR(MAX)),
                CAST(Column_52 AS VARCHAR(MAX)),
                CAST(Column_53 AS VARCHAR(MAX)),
                CAST(Column_54 AS VARCHAR(MAX)),
                CAST(Column_55 AS VARCHAR(MAX)),
                CAST(Column_56 AS VARCHAR(MAX)),
                CAST(Column_57 AS VARCHAR(MAX)),
                CAST(Column_58 AS VARCHAR(MAX)),
                CAST(Column_59 AS VARCHAR(MAX)),
                CAST(Column_60 AS VARCHAR(MAX)),
                CAST(Column_61 AS VARCHAR(MAX)),
                CAST(Column_62 AS VARCHAR(MAX)),
                CAST(Column_63 AS VARCHAR(MAX)),
                CAST(Column_64 AS VARCHAR(MAX)),
                CAST(Column_65 AS VARCHAR(MAX)),
                CAST(Column_66 AS VARCHAR(MAX)),
                CAST(Column_67 AS VARCHAR(MAX)),
                CAST(Column_68 AS VARCHAR(MAX)),
                CAST(Column_69 AS VARCHAR(MAX)),
                CAST(Column_70 AS VARCHAR(MAX)),
                CAST(Column_71 AS VARCHAR(MAX)),
                CAST(Column_72 AS VARCHAR(MAX)),
                CAST(Column_73 AS VARCHAR(MAX)),
                CAST(Column_74 AS VARCHAR(MAX)),
                CAST(Column_75 AS VARCHAR(MAX)),
                CAST(Column_76 AS VARCHAR(MAX)),
                CAST(Column_77 AS VARCHAR(MAX)),
                CAST(Column_78 AS VARCHAR(MAX)),
                CAST(Column_79 AS VARCHAR(MAX)),
                CAST(Column_80 AS VARCHAR(MAX)),
                CAST(Column_81 AS VARCHAR(MAX)),
                CAST(Column_82 AS VARCHAR(MAX)),
                CAST(Column_83 AS VARCHAR(MAX)),
                CAST(Column_84 AS VARCHAR(MAX)),
                CAST(Column_85 AS VARCHAR(MAX)),
                CAST(Column_86 AS VARCHAR(MAX)),
                CAST(Column_87 AS VARCHAR(MAX)),
                CAST(Column_88 AS VARCHAR(MAX)),
                CAST(Column_89 AS VARCHAR(MAX)),
                CAST(Column_90 AS VARCHAR(MAX)),
                CAST(Column_91 AS VARCHAR(MAX)),
                CAST(Column_92 AS VARCHAR(MAX)),
                CAST(Column_93 AS VARCHAR(MAX)),
                CAST(Column_94 AS VARCHAR(MAX)),
                CAST(Column_95 AS VARCHAR(MAX)),
                CAST(Column_96 AS VARCHAR(MAX)),
                CAST(Column_97 AS VARCHAR(MAX)),
                CAST(Column_98 AS VARCHAR(MAX)),
                CAST(Column_99 AS VARCHAR(MAX)),
                CAST(Column_100 AS VARCHAR(MAX)),
                CAST(Column_101 AS VARCHAR(MAX)),
                CAST(Column_102 AS VARCHAR(MAX)),
                CAST(Column_103 AS VARCHAR(MAX)),
                CAST(Column_104 AS VARCHAR(MAX)),
                CAST(Column_105 AS VARCHAR(MAX)),
                CAST(Column_106 AS VARCHAR(MAX)),
                CAST(Column_107 AS VARCHAR(MAX)),
                CAST(Column_108 AS VARCHAR(MAX)),
                CAST(Column_109 AS VARCHAR(MAX)),
                CAST(Column_110 AS VARCHAR(MAX)),
                CAST(Column_111 AS VARCHAR(MAX)),
                CAST(Column_112 AS VARCHAR(MAX)),
                CAST(Column_113 AS VARCHAR(MAX)),
                CAST(Column_114 AS VARCHAR(MAX)),
                CAST(Column_115 AS VARCHAR(MAX)),
                CAST(Column_116 AS VARCHAR(MAX)),
                CAST(Column_117 AS VARCHAR(MAX)),
                CAST(Column_118 AS VARCHAR(MAX)),
                CAST(Column_119 AS VARCHAR(MAX)),
                CAST(Column_120 AS VARCHAR(MAX)),
                CAST(Column_121 AS VARCHAR(MAX)),
                CAST(Column_122 AS VARCHAR(MAX)),
                CAST(Column_123 AS VARCHAR(MAX)),
                CAST(Column_124 AS VARCHAR(MAX)),
                CAST(Column_125 AS VARCHAR(MAX)),
                CAST(Column_126 AS VARCHAR(MAX)),
                CAST(Column_127 AS VARCHAR(MAX)),
                CAST(Column_128 AS VARCHAR(MAX)),
                CAST(Column_129 AS VARCHAR(MAX)),
                CAST(Column_130 AS VARCHAR(MAX)),
                CAST(Column_131 AS VARCHAR(MAX)),
                CAST(Column_132 AS VARCHAR(MAX)),
                CAST(Column_133 AS VARCHAR(MAX)),
                CAST(Column_134 AS VARCHAR(MAX)),
                CAST(Column_135 AS VARCHAR(MAX)),
                CAST(Column_136 AS VARCHAR(MAX)),
                CAST(Column_137 AS VARCHAR(MAX)),
                CAST(Column_138 AS VARCHAR(MAX)),
                CAST(Column_139 AS VARCHAR(MAX)),
                CAST(Column_140 AS VARCHAR(MAX)),
                CAST(Column_141 AS VARCHAR(MAX)),
                CAST(Column_142 AS VARCHAR(MAX)),
                CAST(Column_143 AS VARCHAR(MAX)),
                CAST(Column_144 AS VARCHAR(MAX)),
                CAST(Column_145 AS VARCHAR(MAX)),
                CAST(Column_146 AS VARCHAR(MAX)),
                CAST(Column_147 AS VARCHAR(MAX)),
                CAST(Column_148 AS VARCHAR(MAX)),
                CAST(Column_149 AS VARCHAR(MAX)),
                CAST(Column_150 AS VARCHAR(MAX)),
                CAST(Column_151 AS VARCHAR(MAX)),
                CAST(Column_152 AS VARCHAR(MAX)),
                CAST(Column_153 AS VARCHAR(MAX)),
                CAST(Column_154 AS VARCHAR(MAX)),
                CAST(Column_155 AS VARCHAR(MAX)),
                CAST(Column_156 AS VARCHAR(MAX)),
                CAST(Column_157 AS VARCHAR(MAX)),
                CAST(Column_158 AS VARCHAR(MAX)),
                CAST(Column_159 AS VARCHAR(MAX)),
                CAST(Column_160 AS VARCHAR(MAX)),
                CAST(Column_161 AS VARCHAR(MAX)),
                CAST(Column_162 AS VARCHAR(MAX)),
                CAST(Column_163 AS VARCHAR(MAX)),
                CAST(Column_164 AS VARCHAR(MAX)),
                CAST(Column_165 AS VARCHAR(MAX)),
                CAST(Column_166 AS VARCHAR(MAX)),
                CAST(Column_167 AS VARCHAR(MAX)),
                CAST(Column_168 AS VARCHAR(MAX)),
                CAST(Column_169 AS VARCHAR(MAX)),
                CAST(Column_170 AS VARCHAR(MAX)),
                CAST(Column_171 AS VARCHAR(MAX)),
                CAST(Column_172 AS VARCHAR(MAX)),
                CAST(Column_173 AS VARCHAR(MAX)),
                CAST(Column_174 AS VARCHAR(MAX)),
                CAST(Column_175 AS VARCHAR(MAX)),
                CAST(Column_176 AS VARCHAR(MAX)),
                CAST(Column_177 AS VARCHAR(MAX)),
                CAST(Column_178 AS VARCHAR(MAX)),
                CAST(Column_179 AS VARCHAR(MAX)),
                CAST(Column_180 AS VARCHAR(MAX)),
                CAST(Column_181 AS VARCHAR(MAX)),
                CAST(Column_182 AS VARCHAR(MAX)),
                CAST(Column_183 AS VARCHAR(MAX)),
                CAST(Column_184 AS VARCHAR(MAX)),
                CAST(Column_185 AS VARCHAR(MAX)),
                CAST(Column_186 AS VARCHAR(MAX)),
                CAST(Column_187 AS VARCHAR(MAX)),
                CAST(Column_188 AS VARCHAR(MAX)),
                CAST(Column_189 AS VARCHAR(MAX)),
                CAST(Column_190 AS VARCHAR(MAX)),
                CAST(Column_191 AS VARCHAR(MAX)),
                CAST(Column_192 AS VARCHAR(MAX)),
                CAST(Column_193 AS VARCHAR(MAX)),
                CAST(Column_194 AS VARCHAR(MAX)),
                CAST(Column_195 AS VARCHAR(MAX)),
                CAST(Column_196 AS VARCHAR(MAX)),
                CAST(Column_197 AS VARCHAR(MAX)),
                CAST(Column_198 AS VARCHAR(MAX)),
                CAST(Column_199 AS VARCHAR(MAX)),
                CAST(Column_200 AS VARCHAR(MAX))
            )
        ), 2) AS hash

    from source
)

select * from renamed
